### PR TITLE
MGDAPI-2681 Showing dashboards in OO grafana

### PR DESCRIPTION
**Pull request by Boomatang**
# Issue link

https://issues.redhat.com/browse/MGDAPI-2681

# What

Moving the dashboards from the old monitoring stack to the new.

# Verification steps

- Install this branch
- Log into the Grafana found in the `redhat-rhoam-observability` namespace. Get route `oc get routes -n redhat-rhoam-observability --no-headers | grep grafana | awk '{print $2}' | xargs -I {} echo https://{}`
- Check that the dashboards are all in grafana. 
  - current problem is the sso dashboards are not being picked up
  - Data will not be showing in the dashboards. This is should be fixed in a different ticket

Expected Dashboards
- Critical SLO summary
- CRO Resources
- Endpoints Detailed
- Endpoints Report
- Endpoints Summary
- Resource Usage By Namespace
- Resource Usage for Cluster
- SLO SSO Availability - 5 xx HAProxy Errors

Currently Missing Dashboards
- Keycloak Metrics (Folders: redhat-rhoam-rhsso,  redhat-rhoam-user-sso)

### CODE REVIEW

**Comment by valerymo** [comment]
It's ok for me, if take into consideration notes that this is not final solution for Dashboard, and following will be added/fixed, as noted by Author:
- sso dashboards should be added:
    - redhat-rhoam-rhsso / Keycloak Metrics
    - redhat-rhoam-user-sso / Keycloak Metrics
- Data is not showing in the dashboards. This is should be fixed in a different ticket
Verified on cluster valerym02:  https://grafana-route-redhat-rhoam-observability.apps.valerym02.xskl.s1.devshift.org/d/bdc0992ba5d0ff48f690ec12c056976a92cb080a/resource-usage-for-cluster?search=open&folder=current&orgId=1&refresh=10s
/lgtm

**Comment by laurafitzgerald** [comment]
@Boomatang do we understand what the issue is that is causing the keycloak dashboards to not get loaded? Is there a path forward for that? I'm fine with merging this and a follow on JIRA being created if it simplifies things.

**Comment by Boomatang** [comment]
@laurafitzgerald Yes we understand the problem. When installing the Grafana Operator from OLM it will only look in the same namespace for dashboards. The sso dashboards are not in the same namespace. Peter was looking into a workaround not sure how that is progressing. I will create a JIRA to track this work.

**Comment by Boomatang** [comment]
Changes push was to resolve merge conflicts

**Pull request merged**
